# See https://wiki.hyprland.org/Configuring/Binds/
#!
##! User
bind = Ctrl+Super, Slash, exec, xdg-open ~/.config/illogical-impulse/config.json # Edit shell config
bind = Ctrl+Super+Alt, Slash, exec, xdg-open ~/.config/hypr/custom/keybinds.conf # Edit extra keybinds

# Add stuff here
# Use #! to add an extra column on the cheatsheet
# Use ##! to add a section in that column
# Add a comment after a bind to add a description, like above
unbind = Super, H
unbind = Super, K
unbind = Super, L
unbind = Super, J
unbind = Super, M
unbind = Super+SHIFT, L
unbind = Super+SHIFT, A
unbind = Super+SHIFT, S
unbind = Super+SHIFT, F
unbind = Super+SHIFT, Z
unbind = Super+SHIFT, X
unbind = Super+SHIFT, C
unbind = Super+SHIFT, V

bind = SUPER,R,exec, killall -s SIGUSR1 waybar || waybar
bind = Ctrl+Alt+SHIFT,V,exec, killall -s SIGUSR1 protonvpn-app || protonvpn-app
bind = Super,S, exec, flameshot gui
bind = Super,GRAVE, exec, pkill -SIGUSR1 wayscriber
##! Utilities
bind = SUPER, H,  movefocus, l
bind = SUPER, L, movefocus, r
bind = SUPER, K,    movefocus, u
bind = SUPER, J,  movefocus, d
bind = SUPER+SHIFT, H, movewindow, l
bind = SUPER+SHIFT, J, movewindow, d
bind = SUPER+SHIFT, K, movewindow, u
bind = SUPER+SHIFT, L, movewindow, r
bind = SUPER+SHIFT, A, movetoworkspace,1
bind = SUPER+SHIFT, S, movetoworkspace,2
bind = SUPER+SHIFT, D, movetoworkspace,3
bind = SUPER+SHIFT, F, movetoworkspace,4
bind = SUPER+SHIFT, Z, movetoworkspace,5
bind = SUPER+SHIFT, X, movetoworkspace,6
bind = SUPER+SHIFT, C, movetoworkspace,7
bind = SUPER+SHIFT, V, movetoworkspace,8



bind = SUPER, comma, exec, hyprlock

bind = Super, F,exec, zen-browser
workspace {



unbind = SUPER, 9
unbind = SUPER, 0

bind = SUPER, 1, exec, play  ~/Music/vine-boom-sound.mp3 #1 sine 220 fade l 0 0 .9 gain -10
bind = SUPER, 2, exec, play -n synth 1 sine 247 fade l 0 0 .9 gain -10
bind = SUPER, 3, exec, play -n synth 1 sine 262 fade l 0 0 .9 gain -10
bind = SUPER, 4, exec, play -n synth 1 sine 294 fade l 0 0 .9 gain -10
bind = SUPER, 5, exec, play -n synth 1 sine 330 fade l 0 0 .9 gain -10
bind = SUPER, 6, exec, play -n synth 1 sine 349 fade l 0 0 .9 gain -10
bind = SUPER, 7, exec, play -n synth 1 sine 392 fade l 0 0 .9 gain -10
bind = SUPER, 8, exec, play -n synth 1 sine 440 fade l 0 0 .9 gain -10
bind = SUPER, 9, exec, play -n synth 1 sine 494 fade l 0 0 .9 gain -10
bind = SUPER, 0, exec, play -n synth 1 sine 524 fade l 0 0 .9 gain -10




##! I'm just going to use this as my everything cheatsheet aswell
##! timg is your cli image viewer!
##! Okular is for manga!

}
