# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/
#



bezier = myBezier, 0.05, 0.9, 0.1, 1.05


layerrule = ignore_alpha .1, match:namespace launcher
layerrule = match:namespace launcher, xray 1
layerrule = match:namespace launcher, blur on 
layerrule = match:namespace launcher, animation slide
windowrule = match:class Godot, tile on
windowrule = match:class Aseprite, tile on
windowrule = match:class Godot, workspace 1
windowrule = match:class Aseprite, workspace 2
windowrule = match:class discord, workspace 5
windowrule = match:class vesktop, workspace 5
windowrule = match:class tidal-hifi, workspace 6
windowrule = match:class steam, workspace 2

